# Generated by Django 3.2.7 on 2024-10-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_temperaturerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityWeather',
        ),
    ]
