# Generated by Django 3.2.7 on 2024-10-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_delete_cityweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturerecord',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
