# Generated by Django 3.2.7 on 2024-10-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_temperaturerecord_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturerecord',
            name='description',
            field=models.CharField(default='No description', max_length=255),
        ),
    ]
